### ISSUE TITLE
Fix centrol bot landing page, css&js not loaded

### ISSUE THREAD

**Issue by abin-saju** [centrol-io/centrol_bot#68]
Check by going to:
https://centrol-dev-bot.herokuapp.com

**Comment by mikeCentrol** [comment]
I'm going to make this the simple HTML "Hello from Centrol Trader Bot"

**Comment by mikeCentrol** [comment]
<img width="640" alt="Screen Shot 2021-10-20 at 1 44 32 AM" src="https://user-images.githubusercontent.com/61389419/138034946-5131ec99-5fce-4e0d-9b03-ece47967f3da.png">
